// Generated by uRequire v0.6.14 - template: 'UMD' 
(function (window, global) {
  
var __isAMD = !!(typeof define === 'function' && define.amd),
    __isNode = (typeof exports === 'object'),
    __isWeb = !__isNode;

"use strict";
(function (factory) {
  if (typeof exports === 'object') {
    var nr = new (require('urequire').NodeRequirer) ('mindspace/logger/LogDecorator', module, __dirname, '.');
    module.exports = factory(nr.require, exports, module, nr.require('./LogEnhancer'));
} else if (typeof define === 'function' && define.amd) { define(['require', 'exports', 'module', './LogEnhancer'], factory) } else throw new Error('uRequire: Loading UMD module as <script>, without `build.noLoaderUMD`');
}).call(this, function (require, exports, module, enhanceLoggerFn) {
  

var LogDecorator = function ($provide) {
    $provide.decorator("$log", [
      "$delegate",
      function ($delegate) {
        enhanceLoggerFn($delegate);
        return $delegate;
      }
    ]);
  };
  return [
    "$provide",
    LogDecorator
  ];


})
}).call(this, (typeof exports === 'object' ? global : window), (typeof exports === 'object' ? global : window))