// Generated by uRequire v0.6.14 - template: 'UMD' 
(function (window, global) {
  
var __isAMD = !!(typeof define === 'function' && define.amd),
    __isNode = (typeof exports === 'object'),
    __isWeb = !__isNode;

"use strict";
(function (factory) {
  if (typeof exports === 'object') {
    var nr = new (require('urequire').NodeRequirer) ('mindspace/utils/supplant', module, __dirname, '.');
    module.exports = factory(nr.require, exports, module);
} else if (typeof define === 'function' && define.amd) { define(factory) } else throw new Error('uRequire: Loading UMD module as <script>, without `build.noLoaderUMD`');
}).call(this, function (require, exports, module) {
  

var supplant = function (template, values, pattern) {
    pattern = pattern || /\{([^\{\}]*)\}/g;
    return template.replace(pattern, function (a, b) {
      var p = b.split("."), r = values;
      try {
        for (var s in p) {
          r = r[p[s]];
        }
      } catch (e) {
        r = a;
      }
      return typeof r === "string" || typeof r === "number" ? r : a;
    });
  };
  Function.prototype.method = function (name, func) {
    this.prototype[name] = func;
    return this;
  };
  String.method("supplant", function (values, pattern) {
    var self = this;
    return supplant(self, values, pattern);
  });
  return String.supplant = supplant;


})
}).call(this, (typeof exports === 'object' ? global : window), (typeof exports === 'object' ? global : window))